import { AITool } from "@/types";

export const AI_TOOLS_DATABASE: AITool[] = [
  // ─── MARKETING ───────────────────────────────────────────────
  {
    id: "hubspot-ai",
    name: "HubSpot AI",
    description:
      "All-in-one CRM with AI-powered email marketing, lead scoring, and campaign optimization. Breeze AI suite adds prospecting agents, content generation, and customer support agents.",
    category: "marketing",
    monthlyCost: 45,
    hasFreeTier: true,
    freeTierLimits: "Free CRM with basic email campaigns and forms",
    useCaseTags: ["email marketing", "crm", "lead scoring", "automation"],
    website: "https://hubspot.com",
    tier: "essential",
    pros: [
      "All-in-one ecosystem: CRM, email, ads, SMS, service, and sales automation under one roof",
      "Breeze AI suite (Agents, Intelligence, Studio) adds AI prospecting and content generation",
      "Genuinely usable free CRM tier for small teams — not just a teaser",
      "1,500+ marketplace integrations; seamless marketing-to-sales handoff",
      "Best-in-class multi-touch revenue attribution and campaign analytics at Pro tier",
    ],
    cons: [
      "Brutal pricing cliff: Starter $20/seat/mo jumps to Professional $100/seat/mo (5x increase)",
      "AI features run on credits — heavy use of Breeze Intelligence burns through fast, costs hard to forecast",
      "Breeze Content Agent still needs heavy editing; Prospecting Agent only works with clean CRM data",
      "Customer support quality has declined — long response times on lower-tier plans",
    ],
    bestFor: "Mid-market companies (50-500 employees) wanting a single platform for CRM, marketing automation, and sales enablement",
    avoidIf: "You're a small team on a tight budget — the jump from Starter to Professional is steep, and most AI features are locked behind Pro/Enterprise",
  },
  {
    id: "mailchimp-ai",
    name: "Mailchimp AI",
    description:
      "Email marketing platform with AI Creative Assistant for brand-consistent layouts, send-time optimization, and Customer Journey Builder for automated sequences.",
    category: "marketing",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "250 contacts, 500 emails/month",
    useCaseTags: ["email marketing", "newsletters", "audience segmentation"],
    website: "https://mailchimp.com",
    tier: "recommended",
    pros: [
      "Fastest time-to-first-campaign — new users can send within 30 minutes",
      "AI Creative Assistant generates brand-consistent email layouts from your logo/website",
      "300+ app integrations; Shopify and WooCommerce integrations are particularly strong",
      "Consistently top-tier inbox deliverability rates",
      "Customer Journey Builder (Standard plan) has powerful multi-step automation with branching",
    ],
    cons: [
      "Free plan gutted in 2026 — now only 250 contacts and 500 emails/month",
      "Charges for unsubscribed AND duplicate contacts toward your billing total",
      "Features keep getting removed from lower tiers; phone support only on Premium ($350/mo)",
      "AI-generated content is functional but bland — always needs manual adjustment",
    ],
    bestFor: "Small e-commerce businesses and solo operators needing quick email campaigns with strong Shopify/WooCommerce integrations",
    avoidIf: "You have 10,000+ contacts on a budget — per-contact pricing scales poorly, and duplicate/unsubscribed billing inflates costs",
  },
  {
    id: "surfer-seo",
    name: "Surfer SEO",
    description:
      "Best-in-class on-page content optimization with real-time scoring against top-ranking pages. SERP Analyzer and content audit tools for data-driven SEO.",
    category: "marketing",
    monthlyCost: 99,
    hasFreeTier: false,
    useCaseTags: ["seo", "content optimization", "keyword research"],
    website: "https://surferseo.com",
    tier: "recommended",
    pros: [
      "Best-in-class on-page content editor with real-time scoring for word count, headings, NLP terms",
      "SERP Analyzer compares your content against top 10-50 results with granular data",
      "Audit tool identifies specific gaps in published pages with actionable fixes",
      "User-friendly — non-technical writers can follow recommendations without SEO expertise",
      "Google Docs and WordPress integrations let you optimize in your existing workflow",
    ],
    cons: [
      "Not a complete SEO tool — lacks technical audits, backlink analysis, and rank tracking",
      "Over-optimization risk: following recommendations too literally produces keyword-stuffed content",
      "AI Writer produces factually inaccurate content, especially for niche/local topics",
      "Steep for freelancers at $99/mo with no free tier — only 7-day money-back guarantee",
    ],
    bestFor: "Content marketing teams that already have keyword research covered and need to systematically optimize article content at scale",
    avoidIf: "You need an all-in-one SEO platform (use Semrush/Ahrefs) or plan to use the AI writer without human editing",
  },
  {
    id: "semrush-ai",
    name: "Semrush",
    description:
      "Most comprehensive SEO toolkit: keyword research (26B+ keywords), site audit, rank tracking, backlink analysis, competitive intelligence, and AI visibility tracking.",
    category: "marketing",
    monthlyCost: 140,
    hasFreeTier: true,
    freeTierLimits: "10 requests/day",
    useCaseTags: ["seo", "competitive analysis", "ppc", "content marketing"],
    website: "https://semrush.com",
    tier: "nice-to-have",
    pros: [
      "Most comprehensive SEO toolkit: 26B+ keyword database, site audit, rank tracking, backlink analysis all in one",
      "Competitive intelligence is unmatched — see competitors' top pages, ad spend, and keyword strategies",
      "Best-in-class link building workflow from gap analysis to outreach to monitoring",
      "AI Visibility Toolkit tracks how your brand appears in AI-generated answers (forward-looking)",
      "Site audit catches real technical issues with prioritized fix recommendations",
    ],
    cons: [
      "Billing practices are the #1 complaint (2.1/5 on Trustpilot) — reports of charges after cancellation, difficult cancellation process",
      "Expensive with aggressive upselling: Pro $140/mo, critical add-ons push real costs much higher",
      "Steep learning curve — the sheer feature volume overwhelms new users",
      "Data accuracy varies significantly for non-English and smaller markets",
    ],
    bestFor: "SEO professionals, agencies, and mid-to-large businesses needing comprehensive SEO + competitive intelligence with budget and expertise",
    avoidIf: "You're concerned about billing practices (use a virtual card), only need content optimization (Surfer is cheaper), or can't justify $140+/mo",
  },
  {
    id: "buffer-ai",
    name: "Buffer",
    description:
      "Simplest social media scheduler with AI post suggestions, optimal timing, and support for 12+ platforms including Bluesky and Threads.",
    category: "marketing",
    monthlyCost: 6,
    hasFreeTier: true,
    freeTierLimits: "3 social channels, 10 posts each",
    useCaseTags: ["social media", "scheduling", "analytics"],
    website: "https://buffer.com",
    tier: "recommended",
    pros: [
      "Simplest interface in the category — learning curve measured in minutes, not hours",
      "Per-channel pricing ($5/mo each) is dramatically cheaper than Hootsuite ($99/mo) or Sprout ($199/seat/mo)",
      "Broadest platform support: Instagram, TikTok, LinkedIn, Bluesky, Threads, Pinterest, YouTube, and more",
      "AI Assistant generates post ideas, repurposes content, and adjusts tone directly in the composer",
      "Start Page (link-in-bio builder) included in all plans — replaces Linktree",
    ],
    cons: [
      "Analytics are shallow — no social listening, sentiment analysis, or competitive benchmarking",
      "No unified inbox for DMs, mentions, and comments across platforms",
      "LinkedIn tagging doesn't work from Buffer — must tag manually on LinkedIn",
      "Free tier (10 posts/channel) runs out in days of active posting",
    ],
    bestFor: "Solo creators, freelancers, and small teams (1-5 people) publishing across many platforms on a tight budget",
    avoidIf: "You need deep analytics, social listening, or enterprise community management. Also avoid if LinkedIn tagging is critical for B2B",
  },
  {
    id: "writesonic",
    name: "Writesonic",
    description:
      "AI writing platform with 80+ tools, real-time web research, and direct SEO integrations with Ahrefs and Google Search Console for content at scale.",
    category: "marketing",
    monthlyCost: 39,
    hasFreeTier: true,
    freeTierLimits: "Limited access with GPT-4o mini",
    useCaseTags: ["seo writing", "content marketing", "blog posts", "research"],
    website: "https://writesonic.com",
    tier: "recommended",
    pros: [
      "80+ writing tools covering research, writing, editing, and publishing in one platform",
      "Real-time web research and competitor analysis built into article generation",
      "Direct integrations with Ahrefs, Google Analytics, and Google Search Console",
      "Multi-model access (GPT-4o, Claude 3.5, Gemini) for different tasks",
      "AI Article Writer 6.0 produces factually current long-form content",
    ],
    cons: [
      "Credits don't roll over month-to-month — unused credits lost, hurting variable workloads",
      "Output still requires editing for professional quality — not publish-ready",
      "Advanced features (GEO tracking, AI search visibility) locked behind $399/mo tier",
      "Customer support responsiveness is a recurring complaint",
    ],
    bestFor: "Content marketing teams and SEO professionals running high-volume blog operations",
    avoidIf: "Your workload varies month-to-month (credits expire) or you need only occasional AI writing help",
  },

  // ─── CONTENT CREATION ────────────────────────────────────────
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus",
    description:
      "OpenAI's flagship AI assistant with GPT-5 access, DALL-E 3 image generation, Sora video generation, Advanced Voice Mode, and Custom GPTs — the broadest feature set at $20/mo.",
    category: "content-creation",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Basic GPT access with usage limits and ads",
    useCaseTags: ["writing", "brainstorming", "coding", "research", "image generation"],
    website: "https://chat.openai.com",
    tier: "recommended",
    competitorGroup: "general-ai-assistant",
    pros: [
      "Unmatched breadth: text, image (DALL-E 3), video (Sora), voice mode, and Custom GPTs under one $20/mo subscription",
      "Massive ecosystem — Custom GPT store has specialized tools for nearly every niche task",
      "Best conversational versatility for mixed workflows (writing, code, data analysis in one session)",
      "160 messages per 3 hours with GPT-5 — generous for most individual users",
      "Fastest iteration speed — OpenAI ships new features more frequently than competitors",
    ],
    cons: [
      "Hallucination remains a real issue — fabricates citations, statistics, and URLs with confidence",
      "No persistent memory across projects — context resets between conversations",
      "Free tier now shows ads (since Jan 2026), signaling commercial direction",
      "Weak collaboration — no team workspace or shared conversations in Plus tier",
    ],
    bestFor: "Individual power users who want one subscription covering text, image, voice, and video generation across varied daily tasks",
    avoidIf: "You primarily do long-form analytical writing or need persistent project context — Claude handles these better",
  },
  {
    id: "claude-pro",
    name: "Claude Pro",
    description:
      "Anthropic's AI assistant with superior long-form writing, 200K context window, and Claude Code terminal agent included. Best-in-class for analysis, research, and nuanced reasoning.",
    category: "content-creation",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Limited daily messages",
    useCaseTags: ["writing", "analysis", "research", "coding"],
    website: "https://claude.ai",
    tier: "recommended",
    competitorGroup: "general-ai-assistant",
    pros: [
      "Superior long-form writing and analysis — consistently more nuanced prose than competitors",
      "200K context window processes entire codebases, contracts, and research papers coherently",
      "Claude Code (terminal coding agent) included free with every Pro subscription",
      "Multi-step research synthesis that goes beyond single-query answers",
      "Strongest instruction-following — handles complex, multi-part instructions most reliably",
    ],
    cons: [
      "No image or video generation — text/code only (plus static image analysis)",
      "Rate limits hit harder than expected — ~45 messages per 5-hour window during peak hours",
      "Smaller feature footprint — no voice mode, no plugin store, no custom agent marketplace",
      "Occasional over-cautiousness — sometimes refuses benign tasks due to safety orientation",
    ],
    bestFor: "Writers, researchers, analysts, and developers needing high-quality long-form output and large document analysis",
    avoidIf: "You need an all-in-one creative suite (images, voice, video) or want a large plugin/GPT ecosystem",
  },
  {
    id: "gemini-advanced",
    name: "Gemini Advanced",
    description:
      "Google's AI assistant with deep Workspace integration, 1M token context window, NotebookLM Plus, and 2TB Google Drive storage included — best value if you're in Google's ecosystem.",
    category: "content-creation",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Basic Gemini access",
    useCaseTags: ["writing", "research", "data analysis", "coding"],
    website: "https://gemini.google.com",
    tier: "recommended",
    competitorGroup: "general-ai-assistant",
    pros: [
      "Deep Google Workspace integration — AI directly inside Gmail, Docs, Sheets, and Slides",
      "1M token context window — largest available, ingests entire codebases in a single prompt",
      "2TB Google Drive storage included ($10/mo value alone), making effective AI cost ~$10/mo",
      "NotebookLM Plus included — excellent research tool for AI-powered source document analysis",
      "Strong multimodal reasoning across text, images, audio, and video inputs",
    ],
    cons: [
      "Writing quality lags behind Claude and ChatGPT — adequate but rarely impressive for creative work",
      "Privacy concerns are legitimate given Google's advertising business model",
      "No live support even on paid plans — limited to help articles and community forums",
      "Value drops sharply if you don't use Google Workspace — integration advantage becomes irrelevant",
    ],
    bestFor: "Teams whose daily workflow lives inside Google Workspace (Gmail, Docs, Sheets, Drive) — the integration value is transformative",
    avoidIf: "You don't use Google Workspace, prioritize writing quality above all, or handle sensitive data where Google's data practices concern you",
  },
  {
    id: "jasper",
    name: "Jasper",
    description:
      "AI marketing copywriter with best-in-class Brand Voice training, native SurferSEO integration, 50+ templates, and team collaboration. Unlimited word generation on all plans.",
    category: "content-creation",
    monthlyCost: 49,
    hasFreeTier: false,
    useCaseTags: ["copywriting", "marketing copy", "brand voice", "ads"],
    website: "https://jasper.ai",
    tier: "recommended",
    competitorGroup: "ai-copywriter",
    pros: [
      "Brand Voice is the killer feature — train on your style, tone guides, and past content for consistent team output",
      "Native SurferSEO integration for real-time SEO scoring while writing",
      "50+ purpose-built marketing templates (ads, emails, video scripts, social) — not just prompt wrappers",
      "Team collaboration with shared brand assets, campaign management, and approval workflows",
      "Unlimited word output on all plans — no more watching a word counter",
    ],
    cons: [
      "Expensive for individuals at $49/mo minimum — freelancers get 80% of the value from ChatGPT at $20/mo",
      "Real learning curve — configuring Brand Voice, templates, and Campaign workflows takes time",
      "Output still requires editing — hallucinated statistics, generic phrasing, and repetitive structures appear regularly",
      "Overkill for low-volume creators — ROI doesn't justify cost under 15-20 pieces/month",
    ],
    bestFor: "Marketing teams producing 20+ pieces of branded content per month needing consistent voice, SEO optimization, and team features",
    avoidIf: "You're a solo creator, produce content infrequently, or are comfortable prompting a general AI assistant instead",
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description:
      "AI writing tool with best price-to-value ratio: $29/mo for 5 seats with unlimited words. Multi-model access, workflow automation, and 90+ templates for marketing copy.",
    category: "content-creation",
    monthlyCost: 29,
    hasFreeTier: true,
    freeTierLimits: "Limited free plan for testing",
    useCaseTags: ["copywriting", "product descriptions", "social media"],
    website: "https://copy.ai",
    tier: "recommended",
    competitorGroup: "ai-copywriter",
    pros: [
      "Best price-to-value ratio — $29/mo for 5 seats with unlimited words is remarkably competitive",
      "Genuinely useful free plan for proper testing before committing money",
      "Multi-model AI access — routes queries to different LLMs based on the task",
      "Evolved beyond writing into workflow automation for prospecting and content distribution",
      "Clean, intuitive interface with minimal learning curve — usable content within minutes",
    ],
    cons: [
      "Massive pricing gap: $29/mo jumps to $1,000/mo with nothing in between for growing teams",
      "Long-form content quality trails Jasper — excels at short-form, weaker at blog posts and articles",
      "No built-in collaboration workspace — relies on third-party integrations",
      "Content feels generic at high volumes — repeats patterns and phrases requiring more editing",
    ],
    bestFor: "Freelancers, solopreneurs, and small teams (under 5 people) needing high-volume short-form marketing copy at an affordable price",
    avoidIf: "You need Brand Voice training, SEO-optimized long-form content, or a team larger than 5 but smaller than enterprise",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description:
      "Premier AI image generator with best aesthetic quality. V7 produces stunning visuals, textures, and text rendering. Relax Mode on Standard plan provides effectively unlimited generation.",
    category: "content-creation",
    monthlyCost: 10,
    hasFreeTier: false,
    useCaseTags: ["image generation", "design", "visuals", "branding"],
    website: "https://midjourney.com",
    tier: "recommended",
    pros: [
      "Best aesthetic quality in AI image generation — V7 is a genuine generational leap in textures and detail",
      "Relax Mode on Standard ($30/mo) provides effectively unlimited image generation",
      "Cost-effective vs traditional stock photography — replaces thousands in subscriptions",
      "Strong community and prompt sharing via Discord accelerates learning",
      "Excellent for marketing visuals, product mockups, and brand imagery",
    ],
    cons: [
      "No free trial — you pay before seeing results (unlike DALL-E or Adobe Firefly)",
      "Privacy costs $60/mo — Stealth Mode locked behind Pro tier; Basic/Standard images are public",
      "Discord-based workflow is clunky compared to a dedicated web app",
      "No integration with Photoshop, Figma, or other design tools — manual export/import required",
    ],
    bestFor: "Designers, marketers, and creative professionals needing high-quality visual assets who are willing to learn prompting",
    avoidIf: "You need private generation on a budget (under $60/mo) or tight design software integration",
  },
  {
    id: "canva-ai",
    name: "Canva Pro (AI)",
    description:
      "Design platform with 100M+ assets, 60K+ templates, and 25+ AI tools (Magic Studio). Magic Write, Eraser, Media generation, and Brand Kit for ~$13/mo.",
    category: "content-creation",
    monthlyCost: 13,
    hasFreeTier: true,
    freeTierLimits: "Limited AI features and templates",
    useCaseTags: ["design", "social media graphics", "presentations", "branding"],
    website: "https://canva.com",
    tier: "essential",
    pros: [
      "Extraordinary feature density for ~$13/mo — 100M+ assets, 60K+ templates, 25+ AI tools, unlimited storage",
      "Magic Studio suite: Magic Write, Eraser, Media generation, Background Remover all genuinely useful",
      "Lowest skill floor of any design tool — zero-design-training people produce polished content in an hour",
      "Magic Switch converts one design into multiple formats (post → story → banner → presentation)",
      "Brand Kit enforces logos, fonts, and colors across all templates for on-brand consistency",
    ],
    cons: [
      "Professional designers hit the ceiling fast — limited export formats, no vector editing depth",
      "AI-generated images are low resolution — fine for social media, inadequate for print or hero imagery",
      "Internet connection required — no offline editing capability",
      "Template-based designs are increasingly recognizable as 'Canva designs' — undermines brand distinctiveness",
    ],
    bestFor: "Small business owners, social media managers, and non-designers producing high volumes of visual content quickly",
    avoidIf: "You're a professional designer needing advanced tools, high-res AI imagery, or a distinctive non-template visual brand",
  },
  {
    id: "descript",
    name: "Descript",
    description:
      "Revolutionary text-based video/podcast editor. Edit video by editing the transcript — reduces editing time 60-70%. 30+ AI tools including voice cloning and filler word removal.",
    category: "content-creation",
    monthlyCost: 24,
    hasFreeTier: true,
    freeTierLimits: "1 hour transcription, watermarked exports",
    useCaseTags: ["video editing", "podcast", "transcription", "content repurposing"],
    website: "https://descript.com",
    tier: "nice-to-have",
    pros: [
      "Text-based editing is genuinely revolutionary — reduces editing time 60-70% for spoken-word content",
      "30+ AI tools: Studio Sound, filler word removal, eye contact correction, voice cloning",
      "Best-in-class podcast production — 95% transcription accuracy with direct platform publishing",
      "Real-time team collaboration with commenting on transcript sections",
      "Outstanding student/nonprofit pricing at $5/mo",
    ],
    cons: [
      "Not suitable for complex video — no color grading, VFX, motion graphics, or compositing",
      "AI credit system creates anxiety — failed operations still consume credits",
      "Performance degrades on longer projects — glitchy timelines, random audio drops, lag",
      "Cloud-dependent — no offline editing capability",
    ],
    bestFor: "Podcasters, talking-head YouTubers, course creators, and spoken-word content producers who value speed over pixel-perfect control",
    avoidIf: "You produce cinematic content, music videos, or anything requiring color grading, VFX, or motion graphics",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description:
      "Most realistic AI voice synthesis available. Professional voice cloning, multilingual support in dozens of languages, and expanding into full audio AI suite with music and sound effects.",
    category: "content-creation",
    monthlyCost: 5,
    hasFreeTier: true,
    freeTierLimits: "10,000 characters/month",
    useCaseTags: ["voice synthesis", "voiceover", "audio", "text-to-speech"],
    website: "https://elevenlabs.io",
    tier: "nice-to-have",
    pros: [
      "Most realistic AI voices available — consistently described as indistinguishable from human speech",
      "Extraordinary innovation pace: 8+ major launches in 2025-2026 including speech-to-text and music generation",
      "Exceptional multilingual quality with natural-sounding accents in dozens of languages",
      "Professional voice cloning with high fidelity on Creator plan ($22/mo)",
      "Cost-effective vs voice talent — fraction of the cost per minute for audiobooks and e-learning",
    ],
    cons: [
      "Real costs are 2-3x advertised prices — failed generations, regenerations, and tool requirements inflate spend",
      "Credits burn on failed/glitchy generations with no refund mechanism",
      "Customer support is painfully slow — email-only, 5-14 day response for complex issues",
      "Voice cloning requires careful tuning — not plug-and-play despite marketing",
    ],
    bestFor: "Audiobook producers, e-learning creators, video narrators, and app developers needing high-quality voice synthesis at scale",
    avoidIf: "You need real-time support, work with tight budgets where unpredictable credit consumption is a problem",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description:
      "AI video generation with 140+ avatars in 140+ languages. Creates professional corporate videos without camera, studio, or actors. PowerPoint-to-video conversion included.",
    category: "content-creation",
    monthlyCost: 18,
    hasFreeTier: true,
    freeTierLimits: "3 min/month, 6 avatars",
    useCaseTags: ["video generation", "training videos", "marketing videos"],
    website: "https://synthesia.io",
    tier: "nice-to-have",
    suitableFor: ["enterprise", "saas", "b2b", "sales-team"],
    pros: [
      "Dramatically cheaper than traditional video production — $5K-15K productions for a monthly subscription cost",
      "140+ languages and accents — genuinely useful for multinational localization without re-shooting",
      "140+ diverse AI avatars across ethnicities, genders, ages, and styles",
      "Non-technical users produce polished corporate videos in under an hour",
      "PowerPoint-to-video conversion and access to Veo 3.1/Sora 2 in AI Playground",
    ],
    cons: [
      "Uncanny valley is real — lip-sync imperfections and unnatural eye movements noticeable in motion",
      "Narrow emotional range — excitement, humor, urgency all feel forced; limited to informational content",
      "Content moderation is inconsistent — videos approved one day flagged the next after minor edits",
      "Custom Studio Avatar costs $1,000/year extra on top of subscription",
    ],
    bestFor: "Corporate L&D, HR, and internal comms teams producing high volumes of training and onboarding videos",
    avoidIf: "You need emotionally engaging marketing content or authenticity/human warmth — also avoid if content pushes ambiguous guidelines",
  },
  {
    id: "perplexity-ai",
    name: "Perplexity AI",
    description:
      "AI-powered search engine with inline source citations, multi-model access (GPT-4, Claude), and Copilot Mode for interactive deep research. The best tool for cited, web-grounded answers.",
    category: "content-creation",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Limited searches and model access",
    useCaseTags: ["research", "search", "citations", "fact-checking"],
    website: "https://perplexity.ai",
    tier: "recommended",
    pros: [
      "Live web search with inline source citations — genuine differentiator for research tasks",
      "Multi-model access (GPT-4, Claude, etc.) under one subscription",
      "Copilot Mode refines queries interactively for deeper research than single-shot prompts",
      "Document upload and analysis included in Pro tier",
      "One of the most balanced premium AI subscriptions for the price",
    ],
    cons: [
      "Free tier is heavily restricted in query volume and model access",
      "Reports of accounts being silently downgraded without notification",
      "Weak at creative writing and content generation — it's a search tool, not a general assistant",
      "Can oversimplify complex topics; hallucinations still occur despite citations",
    ],
    bestFor: "Researchers, journalists, analysts, and anyone needing cited, web-grounded answers daily",
    avoidIf: "You primarily need creative writing, code generation, or an all-in-one assistant",
  },
  {
    id: "runway-ml",
    name: "Runway ML",
    description:
      "Cutting-edge AI video generation and editing. Gen-4 model produces highest-quality consumer AI video. Aleph system enables in-video text-based editing without regenerating clips.",
    category: "content-creation",
    monthlyCost: 12,
    hasFreeTier: true,
    freeTierLimits: "Limited access with watermark",
    useCaseTags: ["video generation", "video editing", "motion capture", "creative tools"],
    website: "https://runwayml.com",
    tier: "nice-to-have",
    pros: [
      "Gen-4 model produces the highest-quality AI video among consumer tools",
      "Aleph system allows in-video text-based editing without regenerating entire clips",
      "Act-Two enables motion capture from video references without expensive mocap equipment",
      "Combines text-to-video, image-to-video, and traditional editing in one platform",
      "Backed by Google, Nvidia, Salesforce ($1.5B valuation) — long-term viability",
    ],
    cons: [
      "625 credits on Standard produces only ~2 minutes of video — credits burn fast",
      "Pro plan ($28/mo) required for serious work — Standard is very limited",
      "Quality can be inconsistent across prompts, especially for complex scenes",
      "Credit-based system makes budgeting difficult for production workflows",
    ],
    bestFor: "Filmmakers, content creators, and marketers needing cutting-edge AI video generation and editing",
    avoidIf: "You need high volumes of video on a tight budget or want long-form video generation",
  },
  {
    id: "opus-clip",
    name: "Opus Clip",
    description:
      "AI video repurposing tool that turns long-form videos into 10-25 viral short clips in minutes. Auto-captions, virality scoring, and vertical reframing for TikTok/Reels.",
    category: "content-creation",
    monthlyCost: 15,
    hasFreeTier: true,
    freeTierLimits: "60 processing minutes",
    useCaseTags: ["video clips", "content repurposing", "social media", "short-form video"],
    website: "https://opus.pro",
    tier: "nice-to-have",
    pros: [
      "Saves 8-10 hours of manual editing per batch — paste a URL and get 10-25 clips in minutes",
      "Auto-generated animated captions with ~95% accuracy",
      "AI Virality Score helps prioritize which clips to post",
      "Auto-reframing for vertical (9:16) without manual cropping",
      "10M+ users, 172M+ clips generated — proven market leader",
    ],
    cons: [
      "Expect to discard 20-40% of AI-selected clips — it's a first-draft tool",
      "AI frequently misses context (cuts jokes before punchlines, drops key points)",
      "Low Trustpilot score (~2.4/5) with billing and reliability complaints",
      "TikTok integrations frequently break, requiring re-authentication",
    ],
    bestFor: "YouTubers, podcasters, and social media managers repurposing long-form video into short clips at scale",
    avoidIf: "You need precise editorial control or your content relies on comedic timing and nuanced context",
  },

  // ─── CUSTOMER SUPPORT ────────────────────────────────────────
  {
    id: "intercom-ai",
    name: "Intercom (Fin AI)",
    description:
      "Customer messaging platform with Fin AI agent resolving 67% of support queries across 40M+ conversations. Omnichannel support with deep AI debugging dashboard.",
    category: "customer-support",
    monthlyCost: 74,
    hasFreeTier: false,
    useCaseTags: ["live chat", "ai chatbot", "help desk", "ticketing"],
    website: "https://intercom.com",
    tier: "essential",
    suitableFor: ["saas", "ecommerce", "marketplace", "has-website", "has-app"],
    pros: [
      "Fin AI resolves 67% of queries across 40M+ conversations — genuinely strong out of the box",
      "Omnichannel support (chat, email, social) managed from a single platform",
      "Quick setup — support teams can go live without lengthy onboarding",
      "Deep Fin Optimize Dashboard for debugging and analyzing AI response performance",
      "AI auto-generates and improves help articles directly inside the platform",
    ],
    cons: [
      "Costs are unpredictable at scale — $0.99 per resolution means bills rise as Fin gets better",
      "Hidden add-on fees: Copilot ($35/user), advanced reporting inflate costs 2-3x",
      "Vendor lock-in is real — Fin performs best inside Intercom's ecosystem; migration is painful",
      "AI quality is entirely dependent on your knowledge base content — garbage in, garbage out",
    ],
    bestFor: "Mid-size to large support teams already in Intercom wanting AI to handle a high percentage of repetitive tickets",
    avoidIf: "You have unpredictable ticket volume or tight budgets — the per-resolution model creates billing surprises",
  },
  {
    id: "tidio-ai",
    name: "Tidio AI",
    description:
      "Affordable AI chatbot (Lyro) + live chat combo for small businesses. Automates up to 67% of queries with seamless bot-to-human handoff. No per-agent pricing on core plans.",
    category: "customer-support",
    monthlyCost: 29,
    hasFreeTier: true,
    freeTierLimits: "50 conversations/month",
    useCaseTags: ["chatbot", "live chat", "ecommerce support"],
    website: "https://tidio.com",
    tier: "recommended",
    pros: [
      "Excellent blend of AI chatbot (Lyro), rule-based flows, and live chat in one platform",
      "No per-agent pricing on core plans — adding operators is cost-neutral",
      "Lyro automates up to 67% of customer queries, reducing repetitive workload",
      "4.7/5 on G2 with praise for seamless bot-to-human handoff",
      "Very approachable for non-technical teams — setup takes hours, not weeks",
    ],
    cons: [
      "Pricing is deceptively complex — Lyro AI ($39/mo) and Flows ($29/mo) are separate add-ons, doubling/tripling the price",
      "No flow analytics — impossible to identify and optimize underperforming chatbot paths",
      "Not built for enterprise scale — lacks deep customization and phone support",
    ],
    bestFor: "Small to mid-size e-commerce businesses wanting affordable chatbot + live chat without per-seat pricing",
    avoidIf: "You need enterprise-grade analytics, phone support channels, or deeply customized AI workflows",
  },
  {
    id: "zendesk-ai",
    name: "Zendesk AI",
    description:
      "Most comprehensive ticketing system with AI Copilot saving ~45 seconds per ticket. Intelligent triage, best-in-class reporting, and enterprise-grade security for large support operations.",
    category: "customer-support",
    monthlyCost: 55,
    hasFreeTier: false,
    useCaseTags: ["help desk", "ticketing", "knowledge base", "ai routing"],
    website: "https://zendesk.com",
    tier: "nice-to-have",
    suitableFor: ["enterprise", "saas", "b2b", "sales-team"],
    pros: [
      "Most comprehensive ticketing system on the market with mature, battle-tested workflows",
      "AI Copilot saves ~45 seconds per ticket — 37+ minutes/day per agent at 50 tickets/day",
      "Best-in-class reporting and analytics for support operations",
      "Scales reliably from 10 to 10,000 agents with enterprise security and compliance",
      "Intelligent triage auto-classifies, prioritizes, and routes tickets with high accuracy",
    ],
    cons: [
      "True cost is 2-3x base pricing with AI add-ons — real spend is $150-300/agent/month",
      "AI features gated behind expensive add-ons ($50+/agent/mo) rather than included natively",
      "Steep learning curve for admins — takes weeks to configure properly",
      "Enormous switching costs once you build out workflows — deep vendor lock-in",
    ],
    bestFor: "Mid-size to enterprise support teams (50+ agents) needing robust ticketing, reporting, and compliance at scale",
    avoidIf: "You're a small team or startup — per-agent add-on stacking makes this prohibitively expensive under 20 agents",
  },
  {
    id: "freshdesk-ai",
    name: "Freshdesk (Freddy AI)",
    description:
      "Customer support with Freddy AI for auto-triage, ticket deflection (up to 25% reduction), and no-code AI Agent Studio. More affordable entry than Zendesk for comparable features.",
    category: "customer-support",
    monthlyCost: 15,
    hasFreeTier: true,
    freeTierLimits: "Up to 2 agents",
    useCaseTags: ["ticketing", "ai triage", "email support"],
    website: "https://freshdesk.com",
    tier: "recommended",
    pros: [
      "Freddy suggests help articles before submission, cutting ticket volume by up to 25%",
      "No-code AI Agent Studio lets non-technical staff build and deploy bots",
      "Automatic classification, prioritization, and routing handles traffic spikes",
      "More affordable entry point than Zendesk for comparable core features",
      "Solid multi-channel support across email, chat, phone, and social",
    ],
    cons: [
      "Session-based AI Agent pricing is a budgeting nightmare — high-volume months spike costs",
      "Unused sessions expire each billing cycle with no rollover; AI stops when you run out",
      "At 2,000+ monthly bot sessions, AI costs can exceed your entire base subscription",
      "Freddy AI Copilot currently only works in email channel — no live chat AI assistance",
    ],
    bestFor: "Growing support teams (10-100 agents) wanting AI automation at a lower entry price than Zendesk, primarily on email",
    avoidIf: "You need AI assistance in live chat or non-email channels, or your bot session volume is unpredictable",
  },

  // ─── OPERATIONS ──────────────────────────────────────────────
  {
    id: "zapier",
    name: "Zapier",
    description:
      "Most beginner-friendly automation platform with 7,000+ app integrations. AI Copilot builds automations from plain English. 450+ AI-focused integrations.",
    category: "operations",
    monthlyCost: 30,
    hasFreeTier: true,
    freeTierLimits: "100 tasks/month, 2-step Zaps only",
    useCaseTags: ["automation", "integrations", "workflow", "no-code"],
    website: "https://zapier.com",
    tier: "essential",
    pros: [
      "Most beginner-friendly automation tool — first Zap takes about 3 minutes to build",
      "7,000+ app integrations, more than any competitor by a wide margin",
      "AI Copilot lets you describe automations in plain English and generates the workflow",
      "450+ AI-focused integrations for connecting AI tools into existing workflows",
      "Reliable execution — rarely drops tasks or fails silently",
    ],
    cons: [
      "Costs escalate at scale — every action step counts as a task; a 5-step Zap triggered once = 5 tasks",
      "5,000 tasks/month jumps to $300+/mo; heavy users face $1,000+/mo bills",
      "Free tier is nearly useless: 100 tasks/mo, 2-step only, 15-minute update intervals",
      "No phone or screen-sharing support on any plan",
    ],
    bestFor: "Small businesses and solo operators connecting apps quickly without coding, staying under 2,000 tasks/month",
    avoidIf: "You run high-volume or complex multi-step workflows — per-task pricing will destroy your budget vs Make.com or n8n",
  },
  {
    id: "make",
    name: "Make.com",
    description:
      "Visual automation platform far more powerful than Zapier for complex logic — supports branching, loops, error handling. Native AI modules for OpenAI, Claude, Gemini. Significantly cheaper at scale.",
    category: "operations",
    monthlyCost: 11,
    hasFreeTier: true,
    freeTierLimits: "1,000 credits/month",
    useCaseTags: ["automation", "workflow", "integrations", "visual builder"],
    website: "https://make.com",
    tier: "recommended",
    pros: [
      "Far more powerful than Zapier — branching, loops, error handling, and data transformation natively",
      "1,000+ app integrations with native AI modules for OpenAI, Claude, Gemini, Stability AI",
      "Significantly cheaper than Zapier at scale — starts at $11/mo with non-expiring credits",
      "Visual scenario builder gives a clear map of your entire workflow logic",
      "Free plan with 1,000 operations/month is enough to test serious automations",
    ],
    cons: [
      "Steep learning curve: expect 10-20 hours before productive if new to APIs/data structures",
      "Polling triggers consume credits even when nothing happens, silently eating allocation",
      "Native AI modules charge credit premiums; complex prompts burn hundreds of credits per run",
      "Enterprise volumes can push to five-figure annual pricing unexpectedly",
    ],
    bestFor: "Technical teams and power users needing complex, branching automations at a fraction of Zapier's cost",
    avoidIf: "Your team is non-technical and wants a simple 'set and forget' experience",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description:
      "All-in-one workspace with AI bundled into Business plan ($20/user/mo). Access to GPT-4.1 and Claude 3.7. Notion 3.0 introduced autonomous AI Agents for multi-step workflows.",
    category: "operations",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Limited AI trial, 5MB uploads",
    useCaseTags: ["project management", "docs", "wiki", "ai writing"],
    website: "https://notion.so",
    tier: "essential",
    pros: [
      "AI bundled into Business plan at $20/user/mo — no separate add-on fee",
      "Access to multiple AI models (GPT-4.1 and Claude 3.7) within one subscription",
      "Notion 3.0 introduced autonomous AI Agents for multi-step workflows in your workspace",
      "Natural integration — AI summarizes, drafts, translates, and brainstorms directly in docs and databases",
      "Strong all-in-one workspace replacing docs, wikis, project boards, and notes",
    ],
    cons: [
      "AI only works inside Notion — no cross-tool intelligence if you use Drive, Confluence, or Jira",
      "AI database queries are unreliable — struggles with property-level filters and specific names",
      "Performance degrades significantly on large datasets; heavy databases become sluggish",
      "Full AI features require $20/user/mo Business plan minimum",
    ],
    bestFor: "Teams already living in Notion who want AI writing, summarization, and agents without adding another tool",
    avoidIf: "Your workflows span multiple platforms, or you rely on large databases — scope and performance fall short",
  },
  {
    id: "airtable-ai",
    name: "Airtable AI",
    description:
      "Spreadsheet-database hybrid with AI field types. Multiple views (grid, calendar, gallery, kanban), real-time collaboration, and AI credits bundled into Team/Business plans.",
    category: "operations",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Unlimited bases, 5 editors, 500 AI credits",
    useCaseTags: ["database", "project management", "automation", "data"],
    website: "https://airtable.com",
    tier: "recommended",
    pros: [
      "Spreadsheet-familiar interface — anyone with Excel experience can build a base in 10 minutes",
      "Multiple views (grid, calendar, gallery, kanban) on the same data without duplication",
      "AI credits bundled into Team and Business plans — no separate per-user AI fee",
      "Real-time collaboration with comments, permissions, and version history",
      "Genuinely useful free plan: unlimited bases, 5 editors, 500 AI credits",
    ],
    cons: [
      "Per-seat pricing adds up fast — team of 4 on Team plan costs ~$100/mo monthly billing",
      "The 'collaborator trap': occasional viewers get billed as full seats",
      "No refunds for mid-cycle seat removals — you pay until renewal",
      "AI Agents pricing is variable (per-credit), making costs unpredictable for intensive usage",
    ],
    bestFor: "Ops teams and project managers needing a flexible database with light AI and multiple data views",
    avoidIf: "You have lots of occasional collaborators (per-seat billing punishes you) or need heavy AI processing",
  },
  {
    id: "clickup-ai",
    name: "ClickUp AI",
    description:
      "Feature-dense project management with AI Brain for task summaries, cross-workspace search, and content drafts. Exceptional value at $7-12/user/mo for PM + AI combined.",
    category: "operations",
    monthlyCost: 7,
    hasFreeTier: true,
    freeTierLimits: "100MB storage, unlimited tasks",
    useCaseTags: ["project management", "task management", "docs"],
    website: "https://clickup.com",
    tier: "nice-to-have",
    pros: [
      "Exceptional feature density: task management, docs, whiteboards, goals, time tracking + AI for $7-12/user/mo",
      "ClickUp Brain accesses multiple premium AI models within one subscription",
      "Useful for standups, status checks, cross-workspace search, and quick content drafts",
      "Functional free plan with paid plans starting at just $7/user/mo",
      "Highly customizable views and workflows for nearly any project management style",
    ],
    cons: [
      "AI is a paid add-on ($7/user/mo) charged per seat regardless of whether that user actually uses AI",
      "AI capabilities are genuinely basic — struggles with complex instructions, can't upload files or work on dashboards",
      "Persistent bugs, slow performance, and confusing billing deprioritized vs shipping new features",
      "Overwhelming interface — the sheer number of features creates a steep learning curve",
    ],
    bestFor: "Teams wanting an all-in-one PM tool with basic AI assistance at a low per-seat cost",
    avoidIf: "You need serious AI capabilities or have team members who won't use AI — you're paying per seat regardless",
  },
  {
    id: "n8n",
    name: "n8n",
    description:
      "Open-source workflow automation with 400+ integrations and built-in LLM/AI agent nodes. Self-host for full control or use cloud. Custom JS/Python code in any workflow node.",
    category: "operations",
    monthlyCost: 20,
    hasFreeTier: true,
    freeTierLimits: "Free self-hosted (Community Edition)",
    useCaseTags: ["automation", "open-source", "ai agents", "workflow"],
    website: "https://n8n.io",
    tier: "nice-to-have",
    suitableFor: ["saas", "enterprise", "agency"],
    pros: [
      "Truly open-source with no vendor lock-in — export workflows as JSON, host anywhere",
      "400+ integrations with drag-and-drop visual workflow builder",
      "Built-in LLM/AI agent nodes (LangChain, vector databases) for orchestrating AI workflows",
      "Custom JavaScript/Python code can be embedded in any workflow node",
      "Active community sharing templates, solutions, and custom nodes",
    ],
    cons: [
      "Self-hosting is 'free' but realistically costs $300-800/mo in infrastructure + engineering time",
      "Steep initial learning curve despite visual interface — documentation has gaps",
      "Limited official support — heavy reliance on community forums",
      "Execution-based cloud pricing makes budgeting difficult during peak periods",
    ],
    bestFor: "Technical teams wanting full control over automation infrastructure and needing to build AI agent workflows",
    avoidIf: "You want plug-and-play, zero-config automation, or lack technical resources for self-hosting",
  },

  // ─── SALES ───────────────────────────────────────────────────
  {
    id: "apollo-ai",
    name: "Apollo.io",
    description:
      "All-in-one sales intelligence with 210M+ contacts, email sequences, built-in dialer, and AI meeting intelligence. Replaces 3-4 separate sales tools at one price point.",
    category: "sales",
    monthlyCost: 49,
    hasFreeTier: true,
    freeTierLimits: "Limited credits and contacts",
    useCaseTags: ["lead generation", "email outreach", "sales intelligence"],
    website: "https://apollo.io",
    tier: "essential",
    suitableFor: ["b2b", "saas", "agency", "sales-team"],
    notSuitableFor: ["b2c", "ecommerce"],
    pros: [
      "Massive database: 210M+ contacts and 30M+ companies with advanced filtering",
      "True all-in-one: lead database, email sequences, dialer, and meeting intelligence in one tool",
      "Best value for startups and SMBs — replaces 3-4 separate sales tools",
      "Pro/Org plans include call recording with AI summaries and auto-generated follow-up tasks",
      "Generous free plan for meaningful testing before committing",
    ],
    cons: [
      "Email bounce rates reach 15-20% on some segments; mobile numbers particularly unreliable for enterprise contacts",
      "Credit system is confusing — exports, mobile views, and enrichments all cost credits with silent overages",
      "LinkedIn automation is manual only despite 'multichannel' marketing",
      "Platform slows during peak hours; steep learning curve for full feature adoption",
    ],
    bestFor: "SMB and early-stage sales teams (1-20 reps) needing an affordable, consolidated outbound stack",
    avoidIf: "Data accuracy is mission-critical for your outreach, or you need true LinkedIn automation",
  },
  {
    id: "instantly-ai",
    name: "Instantly.ai",
    description:
      "Cold email platform with unlimited email accounts, built-in warm-up, and 90%+ primary inbox rates. One of the cheapest dedicated cold email tools at $37/mo.",
    category: "sales",
    monthlyCost: 37,
    hasFreeTier: false,
    useCaseTags: ["cold email", "outreach", "email automation"],
    website: "https://instantly.ai",
    tier: "recommended",
    suitableFor: ["b2b", "saas", "agency", "sales-team"],
    notSuitableFor: ["b2c", "ecommerce"],
    pros: [
      "Unlimited email accounts on all plans — distribute volume for better deliverability",
      "Built-in email warm-up eliminates the need for separate warm-up tools",
      "Deliverability consistently strong: 90%+ primary inbox rates on warmed Gmail accounts",
      "Clean, intuitive interface easy to learn even for outreach beginners",
      "Growth plan at $37/mo is one of the cheapest dedicated cold email entry points",
    ],
    cons: [
      "Growth plan is crippled: only 1,000 contacts total, no unified inbox, no A/B testing",
      "No LinkedIn automation whatsoever — missing a key outreach channel",
      "Adding SuperSearch (leads) and CRM modules makes costs match end-to-end platforms like Apollo",
      "Email warm-up frequently disconnects, requiring repeated support interventions",
    ],
    bestFor: "Solo founders and small teams running low-to-medium-volume cold email campaigns prioritizing deliverability",
    avoidIf: "You need multichannel outreach, large contact lists, or A/B testing — forced into expensive upgrades immediately",
  },
  {
    id: "gong-ai",
    name: "Gong",
    description:
      "Best-in-class conversation intelligence: records, transcribes, and analyzes calls to surface what top performers do differently. Deal forecasting more accurate than CRM-based methods.",
    category: "sales",
    monthlyCost: 100,
    hasFreeTier: false,
    useCaseTags: ["call analytics", "sales coaching", "revenue intelligence"],
    website: "https://gong.io",
    tier: "nice-to-have",
    suitableFor: ["b2b", "saas", "enterprise", "sales-team"],
    notSuitableFor: ["b2c", "ecommerce", "content-heavy"],
    pros: [
      "Best-in-class conversation intelligence — surfaces what top performers do differently from real data",
      "Forecasting and deal intelligence measurably more accurate than CRM-based forecasting",
      "Transcription accuracy and call summary quality consistently rated excellent",
      "Coaching insights are genuinely actionable — managers identify specific skill gaps from conversation data",
      "Deep CRM integrations push insights directly into Salesforce, HubSpot, etc.",
    ],
    cons: [
      "Prohibitive pricing: $120-250/user/mo + $5K-50K/year platform fee + $15K-65K implementation",
      "Annual/multi-year contracts only, paid upfront, with 5-15% auto-renewal uplifts and 50-100% early termination penalties",
      "Feature depth goes unused by smaller orgs — paying enterprise prices for capabilities never adopted",
      "Dashboard confusing for new users; AI struggles with fast speech and noisy environments",
    ],
    bestFor: "Sales organizations with 20+ reps and $1M+ ARR who can justify investment through improved win rates",
    avoidIf: "Small team, tight budget, or want flexible billing — Gong's pricing is designed for enterprise buyers only",
  },
  {
    id: "shopify-magic",
    name: "Shopify Magic",
    description:
      "Free AI features built into all Shopify plans: product descriptions, email subject lines, campaign copy in multiple languages, and AI customer replies in Shopify Inbox.",
    category: "sales",
    monthlyCost: 39,
    hasFreeTier: false,
    useCaseTags: ["ecommerce", "product descriptions", "store management"],
    website: "https://shopify.com",
    tier: "essential",
    suitableFor: ["ecommerce", "b2c", "physical-products"],
    notSuitableFor: ["saas", "agency", "content-heavy"],
    pros: [
      "Completely free — included in all Shopify plans with no usage limits",
      "Deeply integrated with direct access to store data and product information",
      "Generates product descriptions and campaign copy in English, Spanish, French, and Chinese",
      "AI customer replies in Shopify Inbox handle basic questions automatically",
      "Optimized email send times improve open rates without manual testing",
    ],
    cons: [
      "Output quality is bland and generic — sounds obviously AI-generated, lacks brand personality",
      "Generated copy almost never goes live without significant manual editing",
      "Cannot handle complex customer questions beyond FAQ-level support",
      "Zero value outside the Shopify ecosystem",
    ],
    bestFor: "Shopify merchants needing quick first drafts of product descriptions and basic email copy at zero extra cost",
    avoidIf: "You need high-quality, brand-specific content or sophisticated AI customer support — this is a convenience feature, not a serious AI tool",
  },
  {
    id: "lemlist",
    name: "Lemlist",
    description:
      "Best-in-class outreach personalization with dynamic images/GIFs embedding prospect data. True multichannel (email, LinkedIn, SMS, calls) with AI-generated sequences.",
    category: "sales",
    monthlyCost: 69,
    hasFreeTier: false,
    useCaseTags: ["outreach", "linkedin", "email sequences", "personalization"],
    website: "https://lemlist.com",
    tier: "recommended",
    suitableFor: ["b2b", "saas", "agency", "sales-team"],
    notSuitableFor: ["b2c", "ecommerce"],
    pros: [
      "Best-in-class personalization: dynamic images and GIFs with prospect names, logos, and screenshots",
      "True multichannel outreach across email, LinkedIn, SMS, and calls from one platform",
      "Exceptionally strong tutorials, templates, and community that accelerate learning",
      "Clean, intuitive interface with minimal learning curve for basic campaigns",
      "AI-generated sequences help create personalized outreach at scale",
    ],
    cons: [
      "Expensive per-seat: LinkedIn features locked behind $99/seat/mo; 5-person team runs $5,940+/year",
      "Chrome extension for LinkedIn prospecting is notoriously unstable — needs repeated reinstalls",
      "Lead database UX is poor — no bulk search, everything must be done line by line",
      "Advanced features (personalized images, conditional logic) have a steeper learning curve than marketed",
    ],
    bestFor: "Sales teams (2-10 people) prioritizing creative, personalized outreach with multichannel capabilities",
    avoidIf: "Large SDR team (per-seat costs compound fast) or heavy LinkedIn prospecting reliance (Chrome extension reliability issues)",
  },

  // ─── ADMIN & PRODUCTIVITY ────────────────────────────────────
  {
    id: "otter-ai",
    name: "Otter.ai",
    description:
      "98% transcription accuracy with AI summaries that turn 60-minute meetings into 3-5 minute briefs. Strong speaker identification. Users report saving 4+ hours/week.",
    category: "admin",
    monthlyCost: 8,
    hasFreeTier: true,
    freeTierLimits: "300 min lifetime, 30 min/meeting",
    useCaseTags: ["meeting notes", "transcription", "ai summaries"],
    website: "https://otter.ai",
    tier: "recommended",
    pros: [
      "98% transcription accuracy with clear audio — genuinely top-tier for English",
      "AI summaries turn 60-minute meetings into 3-5 minute briefs reliably",
      "Strong speaker identification correctly attributes dialogue to participants",
      "Users report saving 4+ hours per week eliminating manual note-taking",
      "Reasonable pricing: Pro at $8.33/mo (annual) is affordable for individuals",
    ],
    cons: [
      "Strict minute caps on all plans (Pro: 300 min/mo, 30 min per conversation) — no unlimited option",
      "File imports capped at 10/month even on Pro — content creators hit this wall fast",
      "Free plan caps at 30 minutes per meeting, creating fragmented transcripts for longer meetings",
      "Per-user pricing means teams pay for capacity even when some members rarely transcribe",
    ],
    bestFor: "Individual professionals and small teams with moderate, predictable English meeting loads",
    avoidIf: "You have long/frequent meetings, need unlimited transcription, or work primarily in non-English languages",
  },
  {
    id: "grammarly-ai",
    name: "Grammarly Pro",
    description:
      "AI writing assistant saving ~30 min/day per user. Works everywhere (browser, desktop, mobile). Style guides and brand tone ensure consistent voice across teams.",
    category: "admin",
    monthlyCost: 12,
    hasFreeTier: true,
    freeTierLimits: "Basic grammar and spelling",
    useCaseTags: ["writing", "grammar", "communication", "brand voice"],
    website: "https://grammarly.com",
    tier: "recommended",
    pros: [
      "Saves ~30 minutes of editing time per day per user — 2.5 hours/week reclaimed",
      "Works everywhere: browser, desktop, mobile, Google Docs, Slack, email clients",
      "Style guide and brand tone features ensure consistent voice across entire team output",
      "Tone detection catches messages that might land poorly before sending",
      "Plagiarism detection included in Pro tier",
    ],
    cons: [
      "Suggestions not always right — can strip personality or suggest genuinely incorrect changes",
      "Poor with technical, scientific, or discipline-specific content — flags correct jargon as errors",
      "Aggressive upselling from free tier; constant upgrade prompts",
      "Pro at $12/user/mo (annual) scales to significant cost for large teams",
    ],
    bestFor: "Marketing, sales, and customer-facing teams producing high volumes of written communication needing brand consistency",
    avoidIf: "Your team writes primarily technical/scientific content — false-positive suggestions will create more work",
  },
  {
    id: "reclaim-ai",
    name: "Reclaim.ai",
    description:
      "AI calendar management that auto-blocks time for deep work, habits, and 1:1s. Smart scheduling adapts to changing priorities in real time. Supports both Google Calendar and Outlook.",
    category: "admin",
    monthlyCost: 8,
    hasFreeTier: true,
    freeTierLimits: "Basic smart scheduling",
    useCaseTags: ["calendar", "scheduling", "time management", "productivity"],
    website: "https://reclaim.ai",
    tier: "nice-to-have",
    pros: [
      "AI automatically finds and blocks time for deep work, habits, and 1:1 meetings",
      "Very affordable: starts at $8/user/mo with a functional free tier",
      "Full Microsoft Outlook support (since Aug 2025) achieving parity with Google Calendar",
      "Responsive support with knowledge base, tutorials, and dedicated success managers",
      "Smart scheduling links and auto-rescheduling adapt to changing priorities in real time",
    ],
    cons: [
      "No native iOS or Android apps — significant limitation for mobile-heavy users",
      "Missed tasks and deadlines don't surface with strong enough alerts",
      "Not a replacement for Calendly — scheduling link features are basic by comparison",
      "Advanced features gated behind higher tiers ($12-18/user/mo)",
    ],
    bestFor: "Knowledge workers and managers drowning in meetings who need AI to protect focus time",
    avoidIf: "You need mobile access (no native apps) or a full-featured scheduling link tool (use Calendly)",
  },
  {
    id: "fireflies-ai",
    name: "Fireflies.ai",
    description:
      "AI meeting assistant with 95% accuracy across 100+ languages. Excellent meeting library with emoji-tagged topic summaries and smart search. Pro at ~$10/mo undercuts competitors.",
    category: "admin",
    monthlyCost: 10,
    hasFreeTier: true,
    freeTierLimits: "800 min storage, 30 AI summary credits",
    useCaseTags: ["meeting notes", "transcription", "crm integration"],
    website: "https://fireflies.ai",
    tier: "nice-to-have",
    pros: [
      "Excellent meeting library UX — scan entire meeting contents in seconds via emoji-tagged topics",
      "95% transcription accuracy across 100+ languages for global teams",
      "Built-in AI summaries, smart search, and topic trackers boost post-meeting productivity",
      "Integrates with Zoom, Teams, Google Meet, and CRM tools",
      "Pro at ~$10/mo (annual) significantly undercuts most competitors",
    ],
    cons: [
      "Accuracy drops with accents, overlapping speech, and technical jargon",
      "Free plan restrictive: 800 min storage, only 30 AI summary credits",
      "Cancellation process reported as clunky and difficult",
      "Active class-action lawsuit (Dec 2025) alleging illegal biometric voiceprint collection — privacy risk",
    ],
    bestFor: "Distributed teams meeting frequently across time zones needing affordable, searchable meeting records",
    avoidIf: "Your organization has strict privacy/compliance requirements — the pending biometric data lawsuit is a red flag",
  },
  {
    id: "loom-ai",
    name: "Loom AI",
    description:
      "Best-in-class async video messaging. Screen + webcam recordings shared via link replace unnecessary meetings. AI auto-titles (84% accuracy), chapters, and summaries.",
    category: "admin",
    monthlyCost: 15,
    hasFreeTier: true,
    freeTierLimits: "5-minute video limit",
    useCaseTags: ["video messaging", "async communication", "screen recording"],
    website: "https://loom.com",
    tier: "recommended",
    pros: [
      "Best-in-class for quick screen + webcam recordings shared via link — replaces unnecessary meetings",
      "AI auto-titles (84% accuracy), auto-chapters, and summaries make videos scannable",
      "Viewer analytics show who watched and engagement levels",
      "Seamless integrations with Slack, Notion, Google Docs, Jira",
      "Simple enough that non-technical team members adopt it immediately",
    ],
    cons: [
      "Free plan's 5-minute limit is frustrating for anything beyond quick updates",
      "Post-Atlassian acquisition: reports of lag, audio sync issues, failed uploads",
      "AI features require $20/user/mo tier — not included in base Business plan",
      "Basic editing — no scripting, hook generation, or content repurposing",
    ],
    bestFor: "Remote/hybrid teams needing async communication to replace status meetings and long email threads",
    avoidIf: "You need a video creation/editing tool, or you want AI content generation rather than simple recording",
  },
  {
    id: "gamma-ai",
    name: "Gamma",
    description:
      "AI presentation builder generating polished decks from text prompts in under a minute. 70M+ users. Gamma 3.0 Agent researches topics, refines content, and restyles through conversation.",
    category: "admin",
    monthlyCost: 8,
    hasFreeTier: true,
    freeTierLimits: "400 AI credits (~10 presentations)",
    useCaseTags: ["presentations", "pitch decks", "documents", "ai design"],
    website: "https://gamma.app",
    tier: "recommended",
    pros: [
      "Generates polished presentations from a text prompt in under a minute",
      "70M+ users, 400M+ presentations created — proven at massive scale",
      "Gamma 3.0 Agent researches topics, refines content, and restyles entire decks conversationally",
      "Modern, responsive card-based design looks better than traditional slides on any device",
      "Generous free tier (400 credits = ~10 presentations) for testing",
    ],
    cons: [
      "PowerPoint export is problematic — exported files need 15-45 minutes of cleanup",
      "Less granular design control than PowerPoint or Keynote for pixel-perfect presentations",
      "AI-generated copy can be generic and repetitive — needs human editing",
      "Post-3.0 credit system charges even for minor edits",
    ],
    bestFor: "Startup pitches, internal decks, and sales proposals — anyone needing good-looking presentations fast without design skills",
    avoidIf: "You need pixel-perfect brand-compliant corporate presentations or rely on PowerPoint export fidelity",
  },

  // ─── ANALYTICS & DATA ───────────────────────────────────────
  {
    id: "mixpanel",
    name: "Mixpanel",
    description:
      "Best-in-class event tracking with funnels, cohort retention, and anomaly detection. 1M free monthly events. 91% user satisfaction across 1,400+ reviews. More powerful than GA4 for product analytics.",
    category: "analytics",
    monthlyCost: 25,
    hasFreeTier: true,
    freeTierLimits: "1M events/month",
    useCaseTags: ["product analytics", "funnels", "user behavior", "retention"],
    website: "https://mixpanel.com",
    tier: "recommended",
    pros: [
      "Best-in-class event tracking — funnels, cohort retention, user profiles, anomaly detection far more powerful than GA4",
      "Generous free plan: 1M monthly events with no credit card required",
      "Real-time data appears quickly, enabling rapid response to behavior changes",
      "40+ native integrations with CRMs, data warehouses, and dev tools",
      "91% user satisfaction rating across 1,400+ reviews",
    ],
    cons: [
      "Event-based pricing gets expensive fast: 10M events runs ~$2,520/month",
      "Group Analytics (essential for B2B account-level analysis) is a paid add-on",
      "Steep learning curve — powerful but dense interface requires significant setup and training",
      "Analytics only — no in-app engagement tools; need separate tools to act on insights",
    ],
    bestFor: "Product-led SaaS companies needing deep behavioral analytics to optimize funnels, retention, and feature adoption",
    avoidIf: "You're a content/media site with simple analytics needs — GA4 covers that for free",
  },
  {
    id: "hotjar-ai",
    name: "Hotjar",
    description:
      "Website heatmaps, session recordings, and AI-powered surveys for qualitative UX insights. Free plan with 20K monthly sessions. AI replay tagging auto-identifies rage clicks and form abandonment.",
    category: "analytics",
    monthlyCost: 49,
    hasFreeTier: true,
    freeTierLimits: "20,000 sessions/month, 1-month retention",
    useCaseTags: ["heatmaps", "user research", "surveys", "ux analytics"],
    website: "https://hotjar.com",
    tier: "recommended",
    pros: [
      "Genuinely useful free plan: 20,000 monthly sessions, session replay, and unlimited heatmaps",
      "Easiest UX analytics tool to learn (4.6/5 ease-of-use) — non-technical marketers can self-serve",
      "AI-powered replay tagging auto-identifies rage clicks, u-turns, and form abandonment",
      "Heatmaps and recordings provide qualitative insights that GA4 completely misses",
      "Quick setup — add one script tag and you're recording within minutes",
    ],
    cons: [
      "Daily session recording caps are restrictive on all plans — high-traffic sites miss data",
      "Steep jump from free to paid ($49/mo) with limited middle-ground options",
      "Post-acquisition pricing increases with confusingly restructured tiers",
      "Not a quantitative analytics tool — still need GA4 or Mixpanel for numbers",
    ],
    bestFor: "UX designers and marketing teams who need to see how users interact with their site through heatmaps and recordings",
    avoidIf: "Very high traffic (session caps limit coverage) or you need quantitative analytics (Hotjar is qualitative only)",
  },
  {
    id: "google-analytics",
    name: "Google Analytics 4",
    description:
      "Free web analytics with ML-powered anomaly detection, user behavior predictions, and conversion insights. Deep integration with Google Ads, Search Console, and BigQuery.",
    category: "analytics",
    monthlyCost: 0,
    hasFreeTier: true,
    freeTierLimits: "Full featured free tier",
    useCaseTags: ["web analytics", "traffic analysis", "conversions"],
    website: "https://analytics.google.com",
    tier: "essential",
    pros: [
      "Free for the vast majority of businesses — handles most analytics needs at zero cost",
      "ML auto-detects traffic anomalies, predicts behavior, and identifies conversion opportunities",
      "Same-day setup vs weeks/months for enterprise alternatives",
      "Deep integration with Google Ads, Search Console, BigQuery, and broader Google ecosystem",
      "Event-based data model is fundamentally more flexible than old session-based tracking",
    ],
    cons: [
      "Data retention limited to 14 months on free tier — historical analysis needs BigQuery (extra cost + technical skill)",
      "Data sampling on complex queries or high-traffic sites — you see estimates, not actuals",
      "Steep learning curve from Universal Analytics — event-based model requires rethinking tracking",
      "Hidden implementation costs: most teams need developers or consultants ($thousands) to set up properly",
    ],
    bestFor: "Any website needing solid web analytics without paying — especially if already in the Google ecosystem",
    avoidIf: "You need long-term data retention, unsampled data at scale, or product-level behavioral analytics (use Mixpanel)",
  },
  {
    id: "tableau-ai",
    name: "Tableau",
    description:
      "Gold standard for data visualization with drag-and-drop dashboards connecting to 75+ data sources. 92% of users praise its ability to unify disparate data systems.",
    category: "analytics",
    monthlyCost: 75,
    hasFreeTier: false,
    useCaseTags: ["data visualization", "business intelligence", "dashboards"],
    website: "https://tableau.com",
    tier: "nice-to-have",
    suitableFor: ["enterprise", "saas", "b2b"],
    pros: [
      "Gold standard for data visualization — drag-and-drop creates stunning interactive dashboards no competitor matches",
      "Connects to 75+ data sources including databases, spreadsheets, and cloud services",
      "92% of users praise its ability to unify disparate data systems into single views",
      "Massive community (Tableau Public, forums, user groups) accelerates learning",
      "Creator license enables sophisticated analysis beyond basic BI tools",
    ],
    cons: [
      "Expensive and confusing licensing: Creator at $75/user/mo, costs rise rapidly with users and Server",
      "25% of users report a steep learning curve — not a self-service tool for casual users",
      "Teams spend 60-80% of time preparing data before Tableau can use it effectively",
      "Performance degrades with large datasets or dashboards with many filters",
    ],
    bestFor: "Data teams at mid-to-large companies building complex dashboards to share with hundreds of stakeholders",
    avoidIf: "Small team without a dedicated data analyst, or your data is messy and unstructured",
  },
];

export function getToolsByCategory(
  category: string
): AITool[] {
  return AI_TOOLS_DATABASE.filter((tool) => tool.category === category);
}

export function getToolById(id: string): AITool | undefined {
  return AI_TOOLS_DATABASE.find((tool) => tool.id === id);
}
