import { BusinessBreakdown, BusinessPlanEdits, SelectedTool, CategoryAnalysis, ToolCategory, CATEGORY_LABELS } from "@/types";

export function businessPlanToMarkdown(
  businessType: string,
  breakdown: BusinessBreakdown,
  tools: SelectedTool[],
  totalMonthlyCost: number,
  budgetUsedPercent: number,
  edits?: BusinessPlanEdits
): string {
  const get = (field: keyof BusinessPlanEdits, fallback: string) =>
    edits?.[field] || fallback;

  const lines: string[] = [];

  lines.push(`# AI Tool Planner Business Plan`);
  lines.push(`**${businessType}**\n`);

  lines.push(`## Executive Summary`);
  lines.push(get("executiveSummary", breakdown.executiveSummary) + "\n");

  lines.push(`## Revenue Strategy`);
  lines.push(get("revenueStrategy", breakdown.revenueStrategy) + "\n");

  lines.push(`## Growth Strategy`);
  lines.push(get("growthStrategy", breakdown.growthStrategy) + "\n");

  lines.push(`## Operations Playbook\n`);
  for (const section of breakdown.operationsPlaybook) {
    lines.push(`### ${section.department} (${section.priority})`);
    lines.push(section.overview + "\n");
    lines.push(`**First Step:** ${section.howToStart}\n`);
    if (section.weeklyTasks.length) {
      lines.push(`**Weekly Tasks:**`);
      for (const t of section.weeklyTasks) lines.push(`- ${t}`);
      lines.push("");
    }
    if (section.monthlyTasks.length) {
      lines.push(`**Monthly Tasks:**`);
      for (const t of section.monthlyTasks) lines.push(`- ${t}`);
      lines.push("");
    }
    if (section.kpis.length) {
      lines.push(`**KPIs:** ${section.kpis.join(", ")}\n`);
    }
  }

  lines.push(`## 90-Day Action Plan\n`);
  for (const item of breakdown.ninetyDayPlan) {
    lines.push(`- **[${item.timeline}]** ${item.task} — ${item.department} *(${item.priority})*`);
  }
  lines.push("");

  lines.push(`## Key Metrics\n`);
  for (const m of breakdown.keyMetrics) lines.push(`- ${m}`);
  lines.push("");

  lines.push(`## Team Recommendations`);
  lines.push(get("teamRecommendations", breakdown.teamRecommendations) + "\n");

  if (breakdown.risks.length) {
    lines.push(`## Risks & Pitfalls\n`);
    for (const r of breakdown.risks) lines.push(`- ${r}`);
    lines.push("");
  }

  lines.push(`## AI Tool Stack`);
  lines.push(`**${tools.length} tools** | $${totalMonthlyCost}/mo | ${budgetUsedPercent}% of budget\n`);
  lines.push(`| Tool | Category | Cost | Why |`);
  lines.push(`|------|----------|------|-----|`);
  for (const t of tools) {
    lines.push(`| ${t.name} | ${CATEGORY_LABELS[t.category]} | $${t.monthlyCost}/mo | ${t.whyRecommended} |`);
  }
  lines.push("");

  lines.push(`---`);
  lines.push(`*Generated by AI Tool Planner*`);

  return lines.join("\n");
}

export function toolStackToMarkdown(
  businessType: string,
  tools: SelectedTool[],
  totalMonthlyCost: number,
  budgetUsedPercent: number,
  categories: CategoryAnalysis[]
): string {
  const lines: string[] = [];

  lines.push(`# AI Tool Stack — ${businessType}`);
  lines.push(`**${tools.length} tools** | **$${totalMonthlyCost}/mo** | **${budgetUsedPercent}% of budget**\n`);

  // Group tools by category
  const toolsByCategory = new Map<ToolCategory, SelectedTool[]>();
  for (const tool of tools) {
    const list = toolsByCategory.get(tool.category) || [];
    list.push(tool);
    toolsByCategory.set(tool.category, list);
  }

  // Sort categories by relevance
  const sorted = [...categories]
    .filter((c) => c.relevanceScore >= 10 && toolsByCategory.has(c.category))
    .sort((a, b) => b.relevanceScore - a.relevanceScore);

  for (const cat of sorted) {
    const catTools = toolsByCategory.get(cat.category) || [];
    if (catTools.length === 0) continue;

    const catTotal = catTools.reduce((sum, t) => sum + t.monthlyCost, 0);
    lines.push(`---\n`);
    lines.push(`## ${CATEGORY_LABELS[cat.category]} (${cat.relevanceScore}% relevant) — $${catTotal}/mo`);
    lines.push(`${cat.reasoning}\n`);

    for (const tool of catTools) {
      const price = tool.monthlyCost === 0 ? "Free" : `$${tool.monthlyCost}/mo`;
      const tierLabel = tool.tier === "essential" ? "ESSENTIAL" : tool.tier === "recommended" ? "RECOMMENDED" : "NICE-TO-HAVE";
      const freeTier = tool.hasFreeTier && tool.freeTierLimits ? ` | Free tier: ${tool.freeTierLimits}` : "";

      lines.push(`### ${tool.name} — ${price} [${tierLabel}]${freeTier}`);
      lines.push(`${tool.description}\n`);
      lines.push(`> *Why recommended:* ${tool.whyRecommended}\n`);

      if (tool.pros && tool.pros.length > 0) {
        lines.push(`**Pros:**`);
        for (const pro of tool.pros) lines.push(`- ${pro}`);
        lines.push("");
      }

      if (tool.cons && tool.cons.length > 0) {
        lines.push(`**Cons:**`);
        for (const con of tool.cons) lines.push(`- ${con}`);
        lines.push("");
      }

      if (tool.bestFor) lines.push(`**Best for:** ${tool.bestFor}`);
      if (tool.avoidIf) lines.push(`**Avoid if:** ${tool.avoidIf}`);
      if (tool.bestFor || tool.avoidIf) lines.push("");

      lines.push(`Website: ${tool.website}\n`);
    }
  }

  // Quick-reference summary table
  lines.push(`---\n`);
  lines.push(`## Quick Reference\n`);
  lines.push(`| Tool | Category | Cost | Tier | Free Tier |`);
  lines.push(`|------|----------|------|------|-----------|`);
  for (const t of tools) {
    const price = t.monthlyCost === 0 ? "Free" : `$${t.monthlyCost}/mo`;
    lines.push(`| ${t.name} | ${CATEGORY_LABELS[t.category]} | ${price} | ${t.tier} | ${t.hasFreeTier ? "Yes" : "No"} |`);
  }
  lines.push("");

  lines.push(`---`);
  lines.push(`*Generated by AI Tool Planner*`);

  return lines.join("\n");
}
